# Generated by Django 3.1.3 on 2020-11-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20201129_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(related_name='group_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
    ]
