# Generated by Django 3.1.3 on 2020-12-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201201_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='idUser',
            new_name='id_receiving',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='usersFollow',
        ),
        migrations.AddField(
            model_name='subscription',
            name='id_giving',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_giving_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
